# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6d2c0230a6c794d8b48f2a27f61891f00fb85e4061293f36a749f218f2d56aeadbb5f10093e68516c4eb3a7302c6b34118925b5737ad473ecc4d13148480d9

test:
  secret_key_base: 96e8cd063eee406a1ebb9a40ebd754c720d60d0a987f256a1478ec9189a519187f9bbb928e6487a676e4008b5de35ce310a73453ce7a8a3319dffbeba5d1252d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
